Add token details
MapColonies/3d-pycsw-helm pull request #9
Opened 2023-05-18 13:40 UTC by netanelC

This PR does:
1. makes the names shorter
2. adds the jwt token parser
3. syncs with raster the helm

2023-05-21 13:30 UTC, RonitKissis commented on config/nginx_root.conf
> -    access_log /var/log/nginx/access.log;
why did you remove this? this is for the elastic logs

2023-05-21 13:31 UTC, RonitKissis commented on config/policy.rego
> +	lower(payload.d[_]) = lower(map_colonies.domain)
what is this tab for?

2023-05-21 13:31 UTC, RonitKissis commented on config/policy.rego
> +	payload.ao[_] = http_request.headers.origin
what is this tab for?

2023-05-21 13:31 UTC, RonitKissis commented on config/policy.rego
> +	payload.ao == http_request.headers.origin
what is this tab for?

2023-05-21 13:32 UTC, RonitKissis commented on config/policy.rego
> +valid_referrer[payload] {
didnt we remove the origin becuase of issues we had in outnet?

2023-05-21 13:32 UTC, RonitKissis commented on config/policy.rego
> +	not payload.ao
what is this tab for?

2023-05-21 13:34 UTC, RonitKissis requested changes
did you deployed it in openshift and saw that everything is running correctly?

2023-05-23 06:28 UTC, netanelC commented on config/nginx_root.conf
> -    access_log /var/log/nginx/access.log;
Didn't know, apologizing

2023-05-23 06:30 UTC, netanelC commented on config/policy.rego
> +	lower(payload.d[_]) = lower(map_colonies.domain)
I just synced from pycsw/helm/raster so we won't be behind. This doesn't mean a thing

2023-05-23 06:30 UTC, netanelC commented on config/policy.rego
> +	payload.ao[_] = http_request.headers.origin
I just synced from pycsw/helm/raster so we won't be behind. This doesn't mean a thing

2023-05-23 06:31 UTC, netanelC commented on config/policy.rego
> +	payload.ao == http_request.headers.origin
I just synced from pycsw/helm/raster so we won't be behind. This doesn't mean a thing

2023-05-23 06:31 UTC, netanelC commented on config/policy.rego
> +	not payload.ao
I just synced from pycsw/helm/raster so we won't be behind. This doesn't mean a thing

2023-05-23 06:38 UTC, netanelC commented on config/policy.rego
> +valid_referrer[payload] {
This is something else that Raster added due to one client. Turned out they don't even use it... I removed it

2023-05-29 08:12 UTC, RonitKissis approved these changes

2023-05-29 08:15 UTC, merged